---
version: "3.9"
services:
  camel:
    image: apache/camel-jbang:4.8.0
    command:
      [
        "run",
        "/src/Config.java",
        "/src/EventData.java",
        "/src/BodyFormater.java",
        "/src/AzuriteEventFromLog.java",
        "/src/KafkaOut.java",
        "/test/KafkaInTesting.java",
      ]

    environment:
      SRC_FOLDER: /
      KAFKA_BROKER: kafka:29092
      AZURITE_URL: "http://127.0.0.1:10000"
      AZURITE_LOG_FOLDER: /logs
      CAMEL_SEEK_FOLDER: /

    volumes:
      - ../src/main/java/org/anasoid/azurite/event/routes:/src
      - ../src/main/java/org/anasoid/azurite/event/test:/test
      - azurite-logs:/logs

volumes:
  azurite-logs:
