---
version: '3'
services:
  azurite-local:
    extends:
      file: docker-compose.azurite.local.yml
      service: azurite-local
    profiles: [ local ]

  azurite-init-local:
    extends:
      file: docker-compose.azurite.local.yml
      service: azurite-init-local


  azurite:
    extends:
      file: docker-compose.azurite.yml
      service: azurite
    profiles: [ docker ]

  azurite-init:
    extends:
      file: docker-compose.azurite.yml
      service: azurite-init
    profiles: [ docker ]

  camel:
    extends:
      file: docker-compose.camel.yml
      service: camel
    profiles: [ docker ]

  kafka:
    extends:
      file: docker-compose.kafka.yml
      service: kafka
    profiles: [ kafka ]
  kafka-ui:
    extends:
      file: docker-compose.kafka.yml
      service: kafka-ui
    profiles: [ kafka ]
    depends_on:
      - kafka

  servicebus:
    extends:
      file: servicebus/docker-compose.servicebus.yml
      service: servicebus
    profiles: [ servicebus ]
    depends_on:
      - sqledge

  sqledge:
    extends:
      file: servicebus/docker-compose.sqledge.yml
      service: sqledge
    profiles: [ servicebus ]

networks:
  default:
    enable_ipv6: false

volumes:
  azurite-logs: