---
version: '3'
services:
  kafka:
    extends:
      file: docker-compose.kafka.yml
      service: kafka
  azurite:
    extends:
      file: docker-compose.azurite.yml
      service: azurite

  camel:
    extends:
      file: docker-compose.camel.yml
      service: camel
    depends_on:
      - kafka
networks:
  default:
    enable_ipv6: false

volumes:
  azurite-logs: