---
version: '3'
services:
  kafka:
    extends:
      file: docker-compose.kafka.yml
      service: kafka
  kafka-ui:
    extends:
      file: docker-compose.kafka.yml
      service: kafka-ui
    depends_on:
      - kafka

  azurite:
    extends:
      file: docker-compose.azurite.yml
      service: azurite

  camel:
    extends:
      file: docker-compose.camel.yml
      service: camel
    depends_on:
      - kafka

  servicebus:
    extends:
      file: servicebus/docker-compose.servicebus.yml
      service: servicebus
    depends_on:
      - sqledge

  sqledge:
    extends:
      file: servicebus/docker-compose.sqledge.yml
      service: sqledge

networks:
  default:
    enable_ipv6: false

volumes:
  azurite-logs: