---
version: "3.9"
services:
  camel:
    build:
      context: ./docker
    command:
      [
        "run",
        "/src/Config.java",
        "/src/EventData.java",
        "/src/BodyFormater.java",
        "/src/AzuriteEventFromLog.java",
        "/src/BrokerSender.java",
        "/src/out/AmqpOut.java",
        "/src/out/KafkaOut.java",
        "/src/out/BlobQueueOut.java"
      ]

    environment:
      TARGET_NAME: BLOB_QUEUE
      KAFKA_BROKER: kafka:29092
      AZURITE_URL: "http://127.0.0.1:10000"
      AMQP_URI: "amqp://servicebus:5672"
      BLOB_QUEUE_ENDPOINT: "http://azurite:10001"

    volumes:
      - ../src/main/java/org/anasoid/azurite/event/routes:/src
      - ../src/main/java/org/anasoid/azurite/event/test:/test
      - azurite-logs:/logs

volumes:
  azurite-logs:
