---
version: "3.9"
services:
  camel:
    build:
      context: ./docker
    command:
      [
        "run",
        "/src/Config.java",
        "/src/EventData.java",
        "/src/BodyFormater.java",
        "/src/AzuriteEventFromLog.java",
        "/src/AmqpOut.java",
        "/src/KafkaOut.java"
      ]

    environment:
      SRC_FOLDER: /
      TARGET_NAME: AMQP
      KAFKA_BROKER: kafka:29092
      AZURITE_URL: "http://127.0.0.1:10000"
      AZURITE_LOG_FOLDER: /logs
      CAMEL_SEEK_FOLDER: /
      AMQP_URI: "amqp://servicebus:5672"

    volumes:
      - ../src/main/java/org/anasoid/azurite/event/routes:/src
      - ../src/main/java/org/anasoid/azurite/event/test:/test
      - azurite-logs:/logs

volumes:
  azurite-logs:
