---
version: "3.9"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command:
      [
        "/bin/sh",
        "-c",
        "azurite -l /data --blobHost 0.0.0.0  --queueHost 0.0.0.0 --tableHost  0.0.0.0 | tee -a /logs/access-azurite.log",
      ]
    ports:
      - "0.0.0.0:${AZURITE_PORT:-10000}:10000"
      - "0.0.0.0:${AZURITE_PORT:-10001}:10001"
    volumes:
      - azurite-logs:/logs

volumes:
  azurite-logs:
